### ISSUE TITLE
The input image should be a square with equal height and weight? How to keep the output image the same size as input?

### ISSUE THREAD

**Issue by jobsfan** [naoto0804/pytorch-inpainting-with-partial-conv#34]
Hi @naoto0804 , I finally got the code running! Thank you for sharing.

I have two problems in using it.
1. how to break the rule for the setted square size? I mean that I have to input a image with a 512x512, the same height and width. Is it possible to input any size of image?

2. the output image are so small grid, Is it possible to output a image the same size with the input?

**Comment by naoto0804** [comment]
1. You can test an arbitrary size since the network is fully-convolutional. During testing, I recommend you to resize the image being closer to `256x256` before feeding it to the model, since the model is trained on that resolution.
2. Please see `evaluation.py` to handle the estimated outputs. I just concatenated them to make grids.
